# Generated by Django 4.2.3 on 2023-07-24 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('percent_change_1h', models.CharField(max_length=100)),
                ('percent_change_24h', models.CharField(max_length=100)),
                ('percent_change_7d', models.CharField(max_length=100)),
                ('market_cap', models.CharField(max_length=100)),
                ('volume_24h', models.CharField(max_length=100)),
                ('circulating_supply', models.CharField(max_length=100)),
            ],
        ),
    ]
